#-------------------------------
# General Site Settings
title: sortedcord
logo: favicon.ico
description: A programmer with a focus on visual identity, creativity and utility.
baseurl: ""
url: "https://sortedcord.tech" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Aditya Gupta
  avatar: 'https://avatars.githubusercontent.com/u/37407370?v=4'


#-------------------------------
# Hero Settings
hero:
  title:
  description: 
  image: '/images/banner.png'


#-------------------------------
# Contact Settings
contact:
  email: aditsuyag@gmail.com # Add your email for contact form
  description: If you have any suggestion, project or even you want to say “hello”, please reach out to me via Email and I will reply you shortly. # Add a description of your form



#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/sortedcord"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/channel/UCl_2PksiLZcXzGiawYHhY_Q/videos?view=0"}
- {icon: "ion-logo-github", link: "https://github.com/sortedcord"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: sortedcord # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: disable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: /blog/:categories/:title:output_ext
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

kramdown:
  parse_block_html: true

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
